language: objective-c
osx_image: xcode7
script:
- xcodebuild -workspace GTFSKit.xcworkspace -scheme GTFSKit -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.0' test
notifications:
  slack:
    secure: BP5PnAiACRnX41vv8zIVqYpGTGDmnC5sWHVu0A/B3JAwLnAUlXFZE4f8vjcuWd9vMHWhSTiQgifOklfsOId5GhvEuunlLPk7j80ZtJX2SWiYZan7LcZKPfKDkLRmCbYsPlWIx7J5N0BH7xvVBXjYunPM1P1gnJjkruSNB1Eh7SmO5K3PMfOMec4xcXILlc3q/LiITy4mfZL+xkn+469CgaPuT/dF0/v6JHzl2b/Z1z4urHUPW/+bnWfzUsAcauy3g3e0fl6EF0HhffnbqMlfE0rqnNWpeH3xUu3H8T9JBbm1dsqkALNZobc5GOVLzhz2YR1IaE8siAFHkQ3oq1s8aiYz2m6plZgIGAblKtQ/Sprds6RcGZpVpbGPAM7bHPNUFr8h/XenMCKsEh7Lf8aT8hqMvGg0JVpx+ToWnV+/YcQ9+gajMGYTjjS9/2YVLNN/Ul4gN8RWcYaYG3+yU5qB6LUrcTH3J4lP4ID8HOhfWMoiP9FYphBVuvC/S4BgXaaI3ZPee4eahwViiTsvUV1xcWaxjdQBCiAWHjx270Q+SU0b5mHZQoYouPVJXyMJ99n+JB5z+ASKeE1I/dH16DbAa515ajDnisxHOnOJmhF8O8LQ1uDbcc/0hm/AoAcotjCYrrfdDtK5qAktdwvX1oYnXwJjlatu4CepVK+kfkYCxlo=
